title = "Falcon BMS"
description = "Normal Checklists"

[[sections]]
title = "Verify Check"

[[sections.steps]]
label = "FUEL MASTER switch"
value = "ON - guard down"

[[sections.steps]]
label = "ENGINE FEED knob"
value = "NORM"

[[sections.steps]]
label = "EPU switch"
value = "NORM - guard down"

[[sections.steps]]
label = "ENG CONT switch"
value = "PRI - guard down"

[[sections.steps]]
label = "THROTTLE"
value = "CUTOFF"

[[sections.steps]]
label = "LD GEAR handle"
value = "Confirm DOWN and LOCKED"

[[sections.steps]]
label = "HOOK switch"
value = "UP"

[[sections.steps]]
label = "MASTER ARM switch"
value = "OFF"

[[sections.steps]]
label = "AIR SOURCE knob"
value = "NORM"
