[[sections]]
title = "Before Engine Start"

[[sections.steps]]
label = "MAIN PWR switch"
value = "BATT"

[[sections.steps.substeps]]
label = "FLCS RLY light"
value = "ON"

[[sections.steps]]
label = "FLCS PWR TEST switch"
value = "TEST and HOLD"

[[sections.steps.substeps]]
label = "ACFT BATT TO FLCS light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS PMG light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS PWR (4) light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS RLY light"
value = "OFF"

[[sections.steps]]
label = "MAIN PWR switch"
value = "MAIN PWR"

[[sections.steps.substeps]]
label = "ELEC SYS light"
value = "ON"

[[sections.steps.substeps]]
label = "HYD/OIL PRESS light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS RLY light"
value = "ON"

[[sections.steps.substeps]]
label = "SEC light"
value = "ON"

[[sections.steps.substeps]]
label = "ENGINE light"
value = "ON"

[[sections.steps]]
label = "EPU GEN & EPU PMG lights"
value = "OFF"

[[sections.steps]]
label = "Communications"
value = "ALL set to UHF BACKUP"

[[sections.steps]]
label = "Canopy"
value = "CLOSED"

[[sections.steps]]
label = "Chocks"
value = "IN PLACE"

[[sections.steps]]
label = "COM1 & COM2 vol. knob"
value = "SET"

[[sections.steps]]
label = "Backup UHF radio"
value = "Establish comms if required"
