[[sections]]
title = "Before Engine Start"

[[sections.steps]]
label = "Main PWR"
value = "BATT"

[[sections.steps.substeps]]
label = "FLCS RLY light"
value = "ON"

[[sections.steps]]
label = "FLCS PWR TEST"
value = "TEST and HOLD"

[[sections.steps.substeps]]
label = "ACFT BATT TO FLCS light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS PMG light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS PWR light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS RLY light"
value = "OFF"

[[sections.steps]]
label = "Main PWR"
value = "MAIN"

[[sections.steps.substeps]]
label = "ELEC SYS light"
value = "ON"

[[sections.steps.substeps]]
label = "HYD/OIL PRESS light"
value = "ON"

[[sections.steps.substeps]]
label = "FLCS RLY light"
value = "ON"

[[sections.steps.substeps]]
label = "SEC light"
value = "ON"

[[sections.steps.substeps]]
label = "ENGINE light"
value = "ON"

[[sections.steps]]
label = "EPU GEN light"
value = "OFF"

[[sections.steps]]
label = "EPU PMG light"
value = "OFF"

[[sections.steps]]
label = "Communications"
value = "ALL TO UHF BACKUP"

[[sections.steps]]
label = "Canopy"
value = "CLOSED"

[[sections.steps]]
label = "Chocks"
value = "IN PLACE"

[[sections.steps]]
label = "COM1 & COM2 vol. knob"
value = "SET"
